server:
  port: 12375

spring:
  cache:
    type: redis
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: tlatmsrud
    password: tla1203#
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace

jwt:
  secret: ENC(s9MlePyeyjYhoNHUgwZ36VetjiEA5g9CS+nIBkHS1yvm2raaXeF9NRsUHDnHs4wXDxoMfDFRiBR71vAAJVbnMahLa4X8B66T)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
