server:
  port: 12376

spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:mysql://localhost:3306/retromall?useSSL=true&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: ENC(ot79q2Iy88CPWViGt/AnvQ==)
    password: ENC(EOh97G7L7FTaRDNiaoCcWYPLuSPQIKDQ)
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace

jwt:
  secret: ENC(s9MlePyeyjYhoNHUgwZ36VetjiEA5g9CS+nIBkHS1yvm2raaXeF9NRsUHDnHs4wXDxoMfDFRiBR71vAAJVbnMahLa4X8B66T)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor