server:
  port: 12376

spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace

jwt:
  secret: testt323t2safdsa
