server:
  port: 12376

spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace

jwt:
  secret: ENC(s9MlePyeyjYhoNHUgwZ36VetjiEA5g9CS+nIBkHS1yvm2raaXeF9NRsUHDnHs4wXDxoMfDFRiBR71vAAJVbnMahLa4X8B66T)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor